language: ruby

addons:
  apt:
    sources:
    - sourceline: 'deb http://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-draft/xUbuntu_12.04/ ./'
      key_url: 'http://download.opensuse.org/repositories/network:/messaging:/zeromq:/git-draft/xUbuntu_12.04/Release.key'
    packages:
    - libsodium-dev
    - libczmq-dev
    - python3
    - "python3-pip"

rvm:
  - ruby-head
  - 2.6.0
  - 2.5.3
  - 2.4.0
  - 2.3.1
  - 2.2.5
  - 2.1.10

before_install:
  - "sudo pip3 install --upgrade setuptools pip"
  - "sudo pip3 install 'jupyter'"

script: bundle exec rake

notifications:
  irc: "chat.freenode.net#sciruby"
