name: CI on Windows

on:
  push:
    branches:
    - master
  pull_request:
    types:
    - opened
    - synchronize
    - reopened

jobs:
  test:
    name: Test
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - windows-latest
        ruby:
        - "3.0"
        - 2.7
        - 2.6
        - 2.5
        - 2.4
        - 2.3
        - mswin
        - mingw

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - name: Install requirements on vcpkg
      run: |
        vcpkg install zeromq:x64-windows
        vcpkg install czmq:x64-windows
        vcpkg install libffi:x64-windows

    - run: pip3 install -r ci/requirements.txt

    - run: bundle install --jobs 4 --retry 3 --without "pycall cztop"

    - name: Run tests
      env:
        ADAPTERS: ffi-rzmq
      run: |
        for adapter in $ADAPTERS; do
          export IRUBY_TEST_SESSION_ADAPTER_NAME=$adapter
          bundle exec rake test TESTOPTS=-v
        done
      shell: bash

    - run: rake build

    - run: gem install pkg/*.gem
